apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: school-pod-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: managex-school  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30