apiVersion: apps/v1
kind: Deployment
metadata:
  name: school
  labels:
    app: managex-school
spec:
  selector:
    matchLabels:
      app: managex-school
  template:
    metadata:
      labels:
        app: managex-school
      annotations:
        kubernetes.io/change-cause: Update to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/managex_school:92183768d52b988f0f99302dde5b728e65ac3dcb-Add-CI-workflow-for-ManageX-School-Dev-environment-pushed-by-surya1005 - Add-CI-workflow-for-ManageX-School-Dev-environment (by surya1005)
    spec:
      volumes:
        - name: school-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: managex-school-secrets
        - name: school-server-configuration
          configMap:
            name: managex-school-server-config
            items:
              - key: default
                path: default
        - name: school-nginx-configuration
          configMap:
            name: managex-school-nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
      containers:
        - name: managex-school
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
            limits:
              cpu: 500m
              memory: 700Mi
          image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/managex_school:92183768d52b988f0f99302dde5b728e65ac3dcb-Add-CI-workflow-for-ManageX-School-Dev-environment-pushed-by-surya1005
