apiVersion: v1
kind: ConfigMap
metadata:
  name: managex-school-dev-nginx-config
  namespace: dev-managex-school
data:
  default: |
    server {
        listen 80;
        listen [::]:80;
        root /var/www/html/public;
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;
        add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept' always;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
        index index.php;
        charset utf-8;
        client_max_body_size 500M;
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }
        location /storage/ {
            alias /var/www/html/storage/;
            access_log off;
            log_not_found off;
        }
        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }
        error_page 404 /index.php;
        location ~ \.php$ {
            fastcgi_pass unix:/run/php/php8.2-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include fastcgi_params;
        }
        location ~ /\.(?!well-known).* {
            deny all;
        }
    }