apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "school-dev-secrets"
  namespace: dev-managex-school
spec:
  provider: aws       
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:Managex-school-dev-kVqmgl
        objectAlias: ".env"
        objectType: "secretsmanager"
    syncSecret: "true"
    rotationPollInterval: "60s"