apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managex-school-dev-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type":"redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"443","StatusCode":"HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/cacda6c3-9dea-4893-9b70-ed93388e9576
spec:
  ingressClassName: alb
  rules: 
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: managex-school-dev-service
                port:
                  number: 80     
  tls:
    - hosts:
        - greatifydev.school
      secretName: tls-secret
