apiVersion: v1
kind: ConfigMap
metadata:
  name: managex-school-stage-nginx-config
  namespace: stage-managex-school
data:
  default: |
   server {
      listen 80;
      listen [::]:80;
      root /var/www/html/public;

      # CORS headers
      add_header 'Access-Control-Allow-Origin' '*' always;
      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;
      add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept' always;
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-Content-Type-Options "nosniff";

      # Index and charset
      index index.php;
      charset utf-8;

      # Client settings
      client_max_body_size 500M;

      # Timeouts
      proxy_read_timeout 0;
      proxy_connect_timeout 0;
      proxy_send_timeout 0;

      # Try files
      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      # Favicon and robots.txt
      location = /favicon.ico { access_log off; log_not_found off; }
      location = /robots.txt  { access_log off; log_not_found off; }

      # Error pages
      error_page 404 /index.php;

      # PHP handling
      location ~ \.php$ {
          fastcgi_pass unix:/run/php/php8.2-fpm.sock;
          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          include fastcgi_params;
      }

      # Deny hidden files
      location ~ /\.(?!well-known).* {
          deny all;
      }
    }
