apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: managex-school-production
namePrefix: managex-
nameSuffix: -production
resources:
  - ../../base
patches:
  - target:
      kind: CronJob
      name: school-cronjob
    patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: school-cronjob
        labels:
          app: school-cronjob
      spec:
        jobTemplate:
          spec:
            template:
              metadata:
                labels:
                  app: school-cronjob
              spec:
                volumes:
                  - name: school-secrets
                    csi:
                      driver: secrets-store.csi.k8s.io
                      readOnly: true
                      volumeAttributes:
                        secretProviderClass: managex-school-secrets-production

  - target:
      kind: Deployment
      name: school
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: school
        labels:
          app: managex-school
      spec:
        selector:
          matchLabels:
            app: managex-school
      spec:
        template:
          metadata:
            labels:
              app: managex-school
          spec:
           volumes:
              - name: school-secrets
                csi:
                  driver: secrets-store.csi.k8s.io
                  readOnly: true
                  volumeAttributes:
                    secretProviderClass: managex-school-secrets-production
              - name: school-server-configuration
                configMap:
                  name: managex-school-server-config-production
              - name: school-nginx-configuration
                configMap:
                  name: managex-school-nginx-config-production
            containers:
              - name: managex-school
                resources:
                  requests:
                    cpu: 1
                    memory: 4Gi
                  limits:
                    cpu: 2
                    memory: 8Gi

  - target:
      kind: Ingress
      name: school-ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: school-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/39c09169-0ac4-43ee-9ba7-627391f0f45e
      spec:
        rules:
          - http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: managex-school-service-production
                      port:
                        number: 80
        tls:
          - hosts:
              - heycampus.app
            secretName: tls-secret

  - target:
      kind: HorizontalPodAutoscaler
      name: school-pod-autoscaler
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: school-pod-autoscaler
      spec:
        scaleTargetRef:
          name: managex-school-production
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 60

  - target:
      kind: SecretProviderClass
      name: school-secrets
    patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: school-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:ManageX-School-Production-lks03l
              objectAlias: ".env"
              objectType: "secretsmanager"


  - target:
      kind: ConfigMap
      name: school-nginx-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: school-nginx-config
      data:
        nginx.conf: |
          user www-data;
          worker_processes auto;
          pid /run/nginx.pid;
          include /etc/nginx/modules-enabled/*.conf;

          events {
              worker_connections 1024;
              multi_accept on;
              use epoll;
          }

          http {
              ##
              # Basic Settings
              ##
              sendfile on;
              tcp_nopush on;
              tcp_nodelay on;
              keepalive_timeout 65;
              types_hash_max_size 2048;
              server_tokens off;
              
              # Global timeout settings
              proxy_read_timeout 600;
              proxy_connect_timeout 600;
              proxy_send_timeout 600;
              fastcgi_read_timeout 600;
              fastcgi_connect_timeout 600;
              fastcgi_send_timeout 600;

              # Global buffer sizes
              client_body_buffer_size 128k;
              client_header_buffer_size 3k;
              large_client_header_buffers 4 8k;
              client_max_body_size 1024M;

              # Global timeouts
              client_body_timeout 12;
              client_header_timeout 12;
              send_timeout 10;

              # Log format
              log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';

              # MIME
              include /etc/nginx/mime.types;
              default_type application/octet-stream;

              ##
              # SSL Settings
              ##
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_prefer_server_ciphers on;
              ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

              ##
              # Logging Settings
              ##
              access_log /var/log/nginx/access.log main;
              error_log /var/log/nginx/error.log;

              ##
              # Gzip Settings
              ##
              gzip on;
              gzip_vary on;
              gzip_proxied any;
              gzip_comp_level 6;
              gzip_buffers 16 8k;
              gzip_http_version 1.1;
              gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

              ##
              # Global error page configuration
              ##
              fastcgi_intercept_errors on;
              proxy_intercept_errors on;
              ##
              # Virtual Host Configs
              ##
              include /etc/nginx/conf.d/*.conf;
              include /etc/nginx/sites-enabled/*;
          }