apiVersion: apps/v1
kind: Deployment
metadata:
  name: managex-school-stg
  labels:
    app: managex-school-stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managex-school-stg
  template:
    metadata:
      labels:
        app: managex-school-stg
    spec:
      containers:
        - name: managex-school-stg
          image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/stage-managex-school:stg-laravel-81a0dd768d2c7c845e166b6740f51f3697209a0d
          imagePullPolicy: Always
          ports:
            - containerPort: 80
