apiVersion: apps/v1
kind: Deployment
metadata:
  name: managex-school-stg
  labels:
    app: managex-school-stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managex-school-stg
  template:
    metadata:
      labels:
        app: managex-school-stg
    spec:
      containers:
        - name: managex-school-stg
          image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/stage-managex-school:stg-laravel-5c7b9005f47f36908a60d020af04b7b4f9988055
          imagePullPolicy: Always
          ports:
            - containerPort: 80
