apiVersion: batch/v1
kind: CronJob
metadata:
  name: school-cronjob
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: school-cronjob
        spec:
          volumes:
            - name: school-secrets
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: managex-school-secrets