apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: school-secrets
spec:
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:Viewsonic-Live-ZZIlzy
        objectAlias: ".env"
        objectType: "secretsmanager"