apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: school-pod-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: viewsonic-school-production