apiVersion: v1
kind: PersistentVolume
metadata:
  name: managex-school-dev-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: dev-school-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-032f2a0c57e607589
  persistentVolumeReclaimPolicy: Retain