apiVersion: batch/v1
kind: CronJob
metadata:
  name: school-cronjob
  labels:
    app: school-cronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Replace"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: school-cronjob
        spec:
          serviceAccountName: school-service
          volumes:
            - name: school-secrets
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: school-secrets
          containers:
            - name: school-cronjob
              image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/managex_school:d7ceb56ab49397b0c34fde3d89e8e0f3c30cb8d1-Include-Git-reference-for-improved-cache-pushed-by-surya1005
              command: ["php", "/var/www/html/artisan", "schedule:run"]
              volumeMounts:
                - name: school-secrets
                  mountPath: "/mnt/secret-store/"
                  readOnly: true
              lifecycle:
                postStart:
                  exec:
                    command: ['sh', '-c', 'cp /mnt/secret-store/.env /var/www/html/.env']
          restartPolicy: OnFailure
