apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: managex-school-pod-autoscaler
  namespace: dev-managex-school
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: managex-school
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
      selectPolicy: Max
