apiVersion: batch/v1
kind: CronJob
metadata:
  name: school-cronjob
  namespace: dev-managex-school
spec:
  schedule: "*/1 * * * *" # Runs every minute
  concurrencyPolicy: "Replace"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: school-cronjob
        spec:
          serviceAccountName: school-service
          volumes:
            - name: school-secrets
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "school-secrets"
          containers:
            - name: school-cronjob
              image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/managex_school:dev-school-3e68c69b97e68aede78abcb90c73c1365330168e
              command: ["php", "/var/www/html/artisan", "schedule:run"]
              volumeMounts:
                - name: school-secrets
                  mountPath: "/mnt/secret-store"
                  readOnly: true
              lifecycle:
                postStart:
                  exec:
                    command: ['sh', '-c', 'cp /mnt/secret-store/.env /var/www/html/.env']
          restartPolicy: OnFailure
