apiVersion: apps/v1
kind: Deployment
metadata:
  name: managex-school
  namespace: dev-managex-school
  labels:
    app: managex-school
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: managex-school
  template:
    metadata:
      labels:
        app: managex-school
      annotations:
        kubernetes.io/change-cause: 'Update to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/stage-managex-school:dev-school-3c48028954cf82db80f2ff74791a3b157f0e045c - students overall attendance report'
    spec:
      serviceAccountName: school-service
      volumes:
        - name: school-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "school-secrets"
        - name: school-nginx-configuration
          configMap:
            name: managex-school-nginx-config
            items:
              - key: default
                path: default
        - name: cache
          emptyDir: {}
        - name: testing
          emptyDir: {}
        - name: sessions
          emptyDir: {}
        - name: views
          emptyDir: {}
        - name: tcpdf
          emptyDir: {}
        - name: pending-files
          emptyDir: {}
        - name: efs-storage
          persistentVolumeClaim:
            claimName: managex-school-pvc
      containers:
        - name: managex-school
          image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/stage-managex-school:dev-school-3c48028954cf82db80f2ff74791a3b157f0e045c
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: cache
              mountPath: /var/www/html/storage/framework/cache
            - name: sessions
              mountPath: /var/www/html/storage/framework/sessions
            - name: views
              mountPath: /var/www/html/storage/framework/views
            - name: testing
              mountPath: /var/www/html/storage/framework/testing
            - name: tcpdf
              mountPath: /var/www/html/storage/app/tcpdf
            - name: pending-files
              mountPath: /var/www/html/resources/pending-files
            - name: school-nginx-configuration
              mountPath: /etc/nginx/sites-available/
            - name: efs-storage
              mountPath: /var/www/html/storage/app/efs
            - name: efs-storage
              mountPath: /var/www/html/storage/app/public
            - name: school-secrets
              mountPath: "/mnt/secret-store"
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    cp -R /mnt/secret-store/.env /var/www/html/.env
                    chmod -R 777 /var/www/html/storage/app/public
