apiVersion: batch/v1
kind: CronJob
metadata:
  name: school-stage-cronjob
  namespace: stage-managex-school
spec:
  schedule: "*/1 * * * *" # Runs every minute
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: school-stage-cronjob
        spec:
          serviceAccountName: school-stage-service
          volumes:
            - name: school-secrets-environment-file
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "school-stage-secrets"
          containers:
            - name: school-stage-cronjob
              image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/stage-managex-school:stage-viewsonic-9b5510ba39b4060bc58bc9b38af6ea2398ab4833
              command: ["php", "/var/www/html/artisan", "schedule:run"]
              volumeMounts:
                - name: school-secrets-environment-file
                  mountPath: "/mnt/secret-store/"
                  readOnly: true
              lifecycle:
                postStart:
                  exec:
                    command: ['sh', '-c', 'cp /mnt/secret-store/.env /var/www/html/.env']
          restartPolicy: OnFailure
