apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managex-school-stage-pvc
  namespace: stage-managex-school
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: stage-school-storage-class