# Kustomization configuration for staging environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage-managex-school
namePrefix: managex-
labels:
  - pairs:
      environment: staging
    includeSelectors: false
    includeTemplates: true

resources:
  - ../../base

# Patches for different Kubernetes resources
patches:
  # Patch for Deployment configuration
  - target:
      kind: Deployment
      name: school
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: school
        labels:
          app: managex-school
      spec:
        template:
          metadata:
            labels:
              app: managex-school
          spec:
            containers:
              - name: managex-school
                resources:
                  requests:
                    cpu: 800m
                    memory: 800Mi
                  limits:
                    cpu: "1"
                    memory: 1Gi

  # Patch for Ingress configuration
  - target:
      kind: Ingress
      name: school-ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: school-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/53053dcd-d173-42cf-9e53-e15c9c64e7e2
          alb.ingress.kubernetes.io/cors-allow-origin: >-
            https://greatifystg.school,https://www.greatifystg.school,https://*.greatifystg.school
      spec:
        rules:
          - http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: managex-school-service
                      port:
                        number: 80
        tls:
          - hosts:
              - greatifystg.school
            secretName: tls-secret

  # Patch for ConfigMap configuration
  - target:
      kind: ConfigMap
      name: school-server-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: school-server-config
      data:
        default: |
          # Map for real scheme from CloudFront
          map $http_x_forwarded_proto $real_scheme {
            default $http_x_forwarded_proto;
            ''      $scheme;
          }


          # HTTP server block - CloudFront will handle HTTPS termination
          server {
            listen 80;
            listen [::]:80;
            server_name greatifystg.school www.greatifystg.school *.greatifystg.school;

            # Set the real IP from CloudFront and ALB
            real_ip_header X-Forwarded-For;
            set_real_ip_from 0.0.0.0/0; 
            real_ip_recursive on;

            # Specify the root directory for your application
            root /var/www/html/public;
            
            # CORS (Cross-Origin Resource Sharing) headers for API access
            set $cors_origin '';
            if ($http_origin ~* ^https?://(localhost:[0-9]+|([a-z0-9-]+\.)?greatifystg\.school(:[0-9]+)?)$) {
                set $cors_origin $http_origin;
            }
            add_header 'Access-Control-Allow-Origin' $cors_origin always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;
            add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept, Authorization' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Vary' 'Origin' always;
            
            # Security headers
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;

            # Specify index files
            index index.php index.html index.htm;

            # Set character encoding
            charset utf-8;

            # Set maximum client body size
            client_max_body_size 1024M;


            # Main location block for handling requests
            location / {
                try_files $uri $uri/ /index.php?$query_string;
            }


            # Handle favicon and robots.txt requests separately
            location = /favicon.ico {
                access_log off;
                log_not_found off;
            }
            
            location = /robots.txt {
                access_log off;
                log_not_found off;
            }


            # Error page handling for 404 errors
            error_page 404 /index.php;


            # Error page handling for 502, 503, and 504 errors
            error_page 502 503 504 /error.html;


            # PHP handling configuration
            location ~ \.php$ {
                include snippets/fastcgi-php.conf;  # Default PHP handling snippet

                # Pass PHP requests to the PHP-FPM socket
                fastcgi_pass unix:/run/php/php8.2-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
            }


            # Restrict access to hidden files
            location ~ /\.(?!well-known).* {
                deny all;
            }


            # Enhance security with rate limiting (Uncomment to enable)
            # limit_req zone=mylimit burst=10 nodelay;
            
            # Enable gzip compression (Uncomment to enable)
            gzip on;
            gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
          }

  # Patch for SecretProviderClass configuration
  - target:
      kind: SecretProviderClass
      name: school-secrets
    patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: school-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:ManageX-School-Stage-1JE97f
              objectAlias: ".env"
              objectType: "secretsmanager"