apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage-managex-school
namePrefix: managex-
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: school
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: school
        labels:
          app: managex-school
      spec:
        template:
          metadata:
            labels:
              app: managex-school
          spec:
            containers:
              - name: managex-school
                resources:
                  requests:
                    cpu: 800m
                    memory: 800Mi
                  limits:
                    cpu: "1"
                    memory: 1Gi

  - target:
      kind: Ingress
      name: school-ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: school-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/53053dcd-d173-42cf-9e53-e15c9c64e7e2
      spec:
        tls:
          - hosts:
              - greatifystg.school
            secretName: tls-secret

  - target:
      kind: SecretProviderClass
      name: school-secrets
    patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: school-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:ManageX-School-Stage-1JE97f
              objectAlias: ".env"
              objectType: "secretsmanager"