apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage-managex-school
namePrefix: managex-
resources:
  - ../../base
patches:
  - target:
      kind: CronJob
      name: school-cronjob
    patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: school-cronjob
        labels:
          app: school-cronjob-stage
      spec:
        jobTemplate:
          spec:
            template:
              metadata:
                labels:
                  app: school-cronjob-stage
              spec:
                containers:
                  - name: school-cronjob

  - target:
      kind: Deployment
      name: school
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: school
        labels:
          app: managex-school-stage
      spec:
        template:
          metadata:
            labels:
              app: managex-school-stage
          spec:
            containers:
              - name: managex-school-stage
                resources:
                  requests:
                    cpu: 800m
                    memory: 800Mi
                  limits:
                    cpu: "1"
                    memory: 1Gi

  - target:
      kind: Ingress
      name: school-ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: school-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/53053dcd-d173-42cf-9e53-e15c9c64e7e2
      spec:
        tls:
          - hosts:
              - greatifystg.school
            secretName: tls-secret

  - target:
      kind: HorizontalPodAutoscaler
      name: school-pod-autoscaler
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: school-pod-autoscaler
      spec:
        scaleTargetRef:
          name: managex-school
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 30

  - target:
      kind: SecretProviderClass
      name: school-secrets
    patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: school-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:ManageX-School-Stage-1JE97f
              objectAlias: ".env"
              objectType: "secretsmanager"

  - target:
      kind: Service
      name: school-service
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: school-service
      spec:
        selector:
          app: managex-school-stage