apiVersion: v1
kind: PersistentVolume
metadata: 
  name: managex-school-predev-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: dev-school-storage-class
  nfs:
    path: /
    server: fs-0fc819519b7960d48.efs.ap-south-1.amazonaws.com
  persistentVolumeReclaimPolicy: Retain