apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managex-school-pvc
  namespace: stage-managex-school
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: stage-school-sc