apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managex-school-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: prod-school-efs-sc