apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managex-school-pvc
  namespace: managex-school-production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: managex-school-production