# Kustomization configuration for Viewsonic production environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: viewsonic-production
namePrefix: viewsonic-
nameSuffix: -production
resources:
  - ../../base
labels:
  - pairs:
      environment: viewsonic-production
    includeSelectors: false
    includeTemplates: true

# Patches for different Kubernetes resources
patches:
  # Patch for CronJob configuration
  - target:
      kind: CronJob
      name: school-cronjob
    patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: school-cronjob
        labels:
          app: school-cronjob
      spec:
        jobTemplate:
          spec:
            template:
              metadata:
                labels:
                  app: school-cronjob
              spec:
                serviceAccountName: viewsonic-secrets-sa
                volumes:
                  - name: school-secrets
                    csi:
                      driver: secrets-store.csi.k8s.io
                      readOnly: true
                      volumeAttributes:
                        secretProviderClass: viewsonic-school-secrets-production

  # Patch for Deployment configuration
  - target:
      kind: Deployment
      name: school
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: school
        labels:
          app: managex-school
      spec:
        template:
          metadata:
            labels:
              app: managex-school
          spec:
            serviceAccountName: viewsonic-secrets-sa
            volumes:
              - name: school-secrets
                csi:
                  driver: secrets-store.csi.k8s.io
                  readOnly: true
                  volumeAttributes:
                    secretProviderClass: viewsonic-school-secrets-production
              - name: school-server-configuration
                configMap:
                  name: viewsonic-school-server-config-production
              - name: school-nginx-configuration
                configMap:
                  name: viewsonic-school-nginx-config-production
              - name: efs-storage
                persistentVolumeClaim:
                  claimName: viewsonic-production-pvc
            containers:
              - name: managex-school
                resources:
                  requests:
                    cpu: 1
                    memory: 4Gi
                  limits:
                    cpu: 2
                    memory: 8Gi

  # Patch for Ingress configuration
  - target:
      kind: Ingress
      name: school-ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: school-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/3fdde8ff-9c5c-40d1-a63e-371718df2174
      spec:
        rules:
          - http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: viewsonic-school-service
                      port:
                        number: 80
        tls:
          - hosts:
              - greatify.dev
            secretName: tls-secret

  # Patch for HorizontalPodAutoscaler configuration
  - target:
      kind: HorizontalPodAutoscaler
      name: school-pod-autoscaler
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: school-pod-autoscaler
      spec:
        scaleTargetRef:
          name: viewsonic-school-production
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 60

  # Patch for SecretProviderClass configuration
  - target:
      kind: SecretProviderClass
      name: school-secrets
    patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: school-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:Viewsonic-Live-ZZIlzy
              objectAlias: ".env"
              objectType: "secretsmanager"

  # Patch for Nginx ConfigMap configuration
  - target:
      kind: ConfigMap
      name: school-nginx-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: school-nginx-config
      data:
        nginx.conf: |
          # Nginx user and process configuration
          user www-data;
          worker_processes auto;
          pid /run/nginx.pid;
          include /etc/nginx/modules-enabled/*.conf;

          # Event handling configuration
          events {
              worker_connections 1024;
              multi_accept on;
              use epoll;
          }

          http {
              ##
              # Basic Settings
              ##
              sendfile on;
              tcp_nopush on;
              tcp_nodelay on;
              keepalive_timeout 65;
              types_hash_max_size 2048;
              server_tokens off;
              
              # Global timeout settings
              proxy_read_timeout 600;
              proxy_connect_timeout 600;
              proxy_send_timeout 600;
              fastcgi_read_timeout 600;
              fastcgi_connect_timeout 600;
              fastcgi_send_timeout 600;

              # Global buffer sizes
              client_body_buffer_size 128k;
              client_header_buffer_size 3k;
              large_client_header_buffers 4 8k;
              client_max_body_size 1024M;

              # Global timeouts
              client_body_timeout 12;
              client_header_timeout 12;
              send_timeout 10;

              # Log format configuration
              log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';

              # MIME type configuration
              include /etc/nginx/mime.types;
              default_type application/octet-stream;

              # SSL/TLS configuration
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_prefer_server_ciphers on;
              ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

              # Logging configuration
              access_log /var/log/nginx/access.log main;
              error_log /var/log/nginx/error.log;

              # Gzip compression configuration
              gzip on;
              gzip_vary on;
              gzip_proxied any;
              gzip_comp_level 6;
              gzip_buffers 16 8k;
              gzip_http_version 1.1;
              gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

              # Error handling configuration
              fastcgi_intercept_errors off;
              proxy_intercept_errors 0ff;

              # Virtual host configuration includes
              include /etc/nginx/conf.d/*.conf;
              include /etc/nginx/sites-enabled/*;
          }