apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: viewsonic-production-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: viewsonic-production-storage-class