apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-managex-school
namePrefix: managex-

resources:
  - ../../base


patches:
  - path: deployment/school-dev-cronjob.yaml
    target:
      kind: CronJob
      name: school-cronjob
  - patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/name
        value: managex-school-cronjob
      - op: replace
        path: /metadata/labels/app
        value: school-cronjob-dev
      - op: replace
        path: /spec/jobTemplate/spec/template/metadata/labels/app
        value: school-cronjob-dev
    target:
      kind: CronJob
      name: school-cronjob   

  - path: deployment/school-dev-deploy.yaml
    target:
      kind: Deployment
      name: school
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: managex-school-dev
      - op: replace
        path: /metadata/labels/app
        value: managex-school-dev
      - op: replace
        path: /spec/selector/matchLabels/app
        value: managex-school-dev
      - op: replace
        path: /spec/template/metadata/labels/app
        value: managex-school-dev
    target:
      kind: Deployment 
      name: school

  - path: deployment/school-dev-ingress.yaml
    target:
      kind: Ingress
      name: school-ingress

  - path: deployment/school-dev-nginx-configmap.yaml
    target:
      kind: ConfigMap
      name: school-nginx-config

  - path: deployment/school-dev-pod-autoscaler.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: school-pod-autoscaler

  - path: deployment/school-dev-secretprovider.yaml
    target:
      kind: SecretProviderClass
      name: school-secrets

  - path: deployment/school-dev-server-configmap.yaml
    target:
      kind: ConfigMap
      name: school-server-config
   
  - path: deployment/school-dev-service.yaml
    target:
      kind: Service
      name: school-service
  - patch: |-
      - op: replace
        path: /spec/selector/app
        value: managex-school-dev
    target:
      kind: Service
      name: school-service