apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-managex-school
namePrefix: managex-
resources:
  - ../../base
patches:
  - target:
      kind: CronJob
      name: school-cronjob
    patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: school-cronjob
        labels:
          app: school-cronjob-dev
      spec:
        jobTemplate:
          spec:
            template:
              metadata:
                labels:
                  app: school-cronjob-dev
              spec:
                volumes:
                  - name: school-secrets
                    csi:
                      volumeAttributes:
                        secretProviderClass: managex-school-secrets
                containers:
                  - name: managex-school-cronjob
                    image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/managex_school:ae976b038c7acb95e8d4d65b458f7dad140a4369-GE-8298--2057-pushed-by-Pugazh09

  - target:
      kind: Deployment
      name: school
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: school
        labels:
          app: managex-school-dev
      spec:
        template:
          metadata:
            labels:
              app: managex-school-dev
            annotations:
              kubernetes.io/change-cause: "Update to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/managex_school:ae976b038c7acb95e8d4d65b458f7dad140a4369-GE-8298--2057-pushed-by-Pugazh09 - GE-8298  (#2057) (by Pugazh09)"
          spec:
            volumes:
              - name: school-secrets
                csi:
                  driver: secrets-store.csi.k8s.io
                  readOnly: true
                  volumeAttributes:
                    secretProviderClass: managex-school-secrets
              - name: school-server-configuration
                configMap:
                  name: managex-school-server-config
              - name: school-nginx-configuration
                configMap:
                  name: managex-school-nginx-config
            containers:
              - name: managex-school
                image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/managex_school:ae976b038c7acb95e8d4d65b458f7dad140a4369-GE-8298--2057-pushed-by-Pugazh09
                resources:
                  requests:
                    cpu: 400m
                    memory: 600Mi
                  limits:
                    cpu: 500m
                    memory: 700Mi

  - target:
      kind: Ingress
      name: school-ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: school-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/cacda6c3-9dea-4893-9b70-ed93388e9576
      spec:
        rules:
          - http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: managex-school-service
                      port:
                        number: 80
        tls:
          - hosts:
              - greatifydev.school
            secretName: tls-secret

  - target:
      kind: HorizontalPodAutoscaler
      name: school-pod-autoscaler
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: school-pod-autoscaler
      spec:
        scaleTargetRef:
          name: managex-school
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 30

  - target:
      kind: SecretProviderClass
      name: school-secrets
    patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: school-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:Managex-school-dev-kVqmgl
              objectAlias: ".env"
              objectType: "secretsmanager"

  - target:
      kind: Service
      name: school-service
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: school-service
      spec:
        selector:
          app: managex-school