name: ManageX-School-Dev-Deploy

on:
  repository_dispatch:
    types: [trigger-dev-deploy]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'Greatify/manageX-school-web-deployment'
          ref: 'dev'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name dev-stg-cluster --region ap-south-1

      - name: Update deployment files
        run: |
          yq -i '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' deployment/school-dev-deploy.yaml
          yq -i '.spec.template.metadata.annotations."kubernetes.io/change-cause" = "Update to ${{ github.event.client_payload.image }}"' deployment/school-dev-deploy.yaml
          yq -i '.spec.jobTemplate.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' deployment/school-dev-cronjob.yaml

      - name: Apply K8s manifests
        run: |
          kubectl apply -f deployment/school-dev-cronjob.yaml -n dev-managex-school
          kubectl apply -f deployment/school-dev-deploy.yaml -n dev-managex-school
          kubectl apply -f deployment/school-dev-service.yaml -n dev-managex-school
          kubectl apply -f deployment/school-dev-ingress.yaml -n dev-managex-school
          kubectl apply -f deployment/school-dev-secretprovider.yaml -n dev-managex-school

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "greatify-code-merger"
          git add -f deployment/school-dev-deploy.yaml deployment/school-dev-cronjob.yaml
          git commit -m "Update deployment image and change cause"
          git push origin dev

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: Greatify/manageX-school-web
          base: stage
          head: dev
          title: "Promote dev to stage"
          body: "This PR promotes the changes from dev to stage."
          branch: promote-dev-to-stage
