name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      deploy_password:
        description: 'Enter deployment password'
        required: true
        type: string

      deploy_branch:
        description: 'Enter branch name to deploy'
        required: true
        type: string

      prod_tag:
        description: 'Tag for the image [e.g: Version-1.0 , HotFix-MNX8]'
        required: true
        type: string

      prod_choice:
        description: 'Deploy To School Production'
        required: false
        type: boolean
        default: false
      viewsonic_choice:
        description: 'Deploy To ViewSonic Production'
        required: false
        type: boolean
        default: false

      full_deploy:
        description: 'Build New Image and Deploy to Production & ViewSonic'
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:        
  Authentication:
    runs-on: ubuntu-latest
    steps:
      - name: Verify deployment password
        id: password-check
        run: |
          CORRECT_PASSWORD="${{ secrets.DEPLOY_PASSWORD }}"
          INPUT_PASSWORD="${{ github.event.inputs.deploy_password }}"
          
          if [[ "$INPUT_PASSWORD" != "$CORRECT_PASSWORD" ]]; then
            echo "::error::Invalid deployment password"
            exit 1
          fi
          echo "Password verified successfully"

      - name: Slack Notification on Wrong Password
        if: steps.password-check.outcome == 'failure'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,eventName,ref,workflow
          author_name: Deployment Security Alert 🚨
          mention: channel
          if_mention: always
          job_name: security-check
          channel: managex-school
          username: manageX-school
          text: |
            🚨 *Unauthorized Deployment Attempt* 
            *User:* `${{ github.actor }}`
            *Workflow:* Deploy to Production
            *Status:* Failed - Invalid Password
            
            This incident has been logged for security monitoring.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  Docker-Build:
    runs-on: ubuntu-latest
    needs: [Authentication]
    if: github.event.inputs.full_deploy == 'true'
    environment: production
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [18.x]
      max-parallel: 4
      fail-fast: true
    outputs:
      commit_sha: ${{ steps.get-commit-sha.outputs.commit_sha }} 
    steps:
      - name: Checkout CodeBase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: '${{ github.event.inputs.deploy_branch }}'
          repository: 'Greatify/manageX-school-web'
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}

      - name: Get Commit SHA
        id: get-commit-sha
        run: |
         echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.12.0
          driver-opts: |
            image=moby/buildkit:v0.12.0
          buildkitd-flags: |
            --debug
            --allow-insecure-entitlement security.insecure
            --allow-insecure-entitlement network.host
          config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]
            [worker.oci]
              max-parallelism = 12
  
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          docker system prune -af
          df -h 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Sanitize tag
        id: sanitize-tag
        run: |
          # Use tr command to explicitly replace spaces with hyphens
          SANITIZED_TAG=$(echo "${{ github.event.inputs.prod_tag }}" | tr ' ' '-')
          echo "Original tag: ${{ github.event.inputs.prod_tag }}"
          echo "After space replacement: ${SANITIZED_TAG}"
          # Now remove any other unwanted characters while preserving hyphens
          SANITIZED_TAG=$(echo "${SANITIZED_TAG}" | tr -cd 'a-zA-Z0-9-.')
          echo "Final sanitized tag: ${SANITIZED_TAG}"
          echo "sanitized_tag=${SANITIZED_TAG}" >> $GITHUB_OUTPUT

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ steps.get-commit-sha.outputs.commit_sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push PHP Laravel image to ECR
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/managex_school_production:${{ steps.get-commit-sha.outputs.commit_sha }}-${{ steps.sanitize-tag.outputs.sanitized_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          platforms: linux/amd64
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Move new cache to cache directory
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Save image tag to file
        run: |
          echo "${{ steps.login-ecr.outputs.registry }}/managex_school_production:${{ steps.get-commit-sha.outputs.commit_sha }}-${{ steps.sanitize-tag.outputs.sanitized_tag }}" > laravel_image_tag.txt

      - name: Upload image tag files
        uses: actions/upload-artifact@v4
        with:
          name: image-tags
          path: |
            laravel_image_tag.txt
          retention-days: 1
          if-no-files-found: error

      - name: Notify on Docker Build Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,message,commit,author,action,eventName,ref
          author_name: 🐳 Docker Build Failed (School Production Environment)
          mention: ${{ github.actor }}
          if_mention: failure
          job_name: Docker Build
          channel: managex-school
          username: manageX-school
          text: |
            ❌ Docker build failed for commit **${{ steps.get-commit-sha.outputs.commit_sha }}** pushed by @${{ github.actor }} in School Production environment.
            *Author:* `${{ github.actor }}`
            Commit ID: ${{ steps.get-commit-sha.outputs.commit_sha }}
            Error: ${{ steps.build-and-push.outputs.error }}
            Error message: ${{ steps.run-tests.outputs.error-message }}
            Please fix the issue and push the changes again. Note: Code is not deployed.
            @${{ github.actor }}, your changes are not deployed because of this issue.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  Deploy-to-Production:
    needs: [Docker-Build]
    runs-on: ubuntu-latest
    if: always() && (github.event.inputs.full_deploy == 'false' || needs.Docker-Build.result == 'success') && github.event.inputs.prod_choice == 'true'
    environment: production
    env:
      CLOUDFRONT_DISTRIBUTION: ENT69MYLPGTUJ
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Download image tag files
        uses: actions/download-artifact@v4
        if: github.event.inputs.full_deploy == 'true'
        with:
          name: image-tags
          path: .
  
      - name: Set image tags as environment variables
        if: github.event.inputs.full_deploy == 'true'
        run: |
          echo "LARAVEL_IMAGE=$(<laravel_image_tag.txt)" >> $GITHUB_ENV
      - name: Update PHP Laravel deployment image tag and change cause
        if: github.event.inputs.full_deploy == 'true'
        run: |
          yq -i '.spec.template.spec.containers[0].image = "${{ env.LARAVEL_IMAGE }}"' k8s/base/deployment/base-deploy.yaml
          yq -i '.spec.template.metadata.annotations."kubernetes.io/change-cause" = "Updated to ${{ env.LARAVEL_IMAGE }}"' k8s/base/deployment/base-deploy.yaml
          yq -i '.spec.jobTemplate.spec.template.spec.containers[0].image = "${{ env.LARAVEL_IMAGE }}"' k8s/base/cronjob/base-cronjob.yaml

      - name: Commit and Push Image Tags
        if: github.event.inputs.full_deploy == 'true'
        run: |
          git pull origin main
          git config --local user.email "suriyanarayanan.s@greatify.ai"
          git config --local user.name "surya1005"
          git add k8s/base/deployment/base-deploy.yaml k8s/base/cronjob/base-cronjob.yaml
          git commit -m "Update deployment image and change cause [Automated] For Production Environment"
          git push origin main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name greatify-production-cluster --region ap-south-1

      - name: Apply K8s Manifests To Production With Validation
        run: |
          kubectl apply -k k8s/overlays/prod --validate=true
          kubectl rollout status deployment/managex-school-production -n managex-school-production --timeout=300s

      - name: CloudFront Invalidation
        run: |
          INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION }} --paths "/*" --query 'Invalidation.Id' --output text)
          echo "Created invalidation: $INVALIDATION_ID"
          aws cloudfront wait invalidation-completed --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION }} --id $INVALIDATION_ID
          
      - name: Slack Notification On Deployment Status
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: author,action,eventName,ref,workflow
          author_name: School Production Deployment Status
          mention: ${{ github.actor }}
          if_mention: success,failure
          job_name: Deploy-to-Production
          channel: managex-school
          username: manageX-school
          text: |
            ${{ job.status == 'success' && format(':rocket: Deployment to School Production environment triggered by @{0} is {1}.', github.actor, job.status) || format(':x: Deployment to School Production environment triggered by @{0} is {1}.', github.actor, job.status) }}
            *Author:* `${{ github.actor }}`
            *Deployment for commit* *${{ needs.Docker-Build.outputs.commit_sha }}* *pushed by* *@${{ github.actor }}* has *${{ job.status }}* in *School Production Environment*.
            *Workflow Run:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            *Message:* *${{ github.event.inputs.prod_tag }}*
            ${{ job.status == 'success' && 'The code has been deployed to School Production Environment. Please check the deployment and verify the changes on the server.' || 'The code has not been deployed to School Production Environment due to failure. Please check the deployment logs for more details.' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}

  Deploy-to-Viewsonic:
    if: always() && (github.event.inputs.full_deploy == 'false' || needs.Docker-Build.result == 'success') && github.event.inputs.viewsonic_choice == 'true'
    needs: [Docker-Build]
    runs-on: ubuntu-latest
    environment: production
    env:
      CLOUDFRONT_DISTRIBUTION: EYW7M7FFROBZN
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.VIEWSONIC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VIEWSONIC_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.VIEWSONIC_AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name viewsonic-production-cluster --region ap-south-1

      - name: Apply K8s Manifests To ViewSonic Production With Validation
        run: |
          kubectl apply -k k8s/overlays/viewsonic --validate=true
          kubectl rollout status deployment/viewsonic-school-production -n viewsonic-production --timeout=300s

      - name: CloudFront Invalidation
        run: |
          INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION }} --paths "/*" --query 'Invalidation.Id' --output text)
          echo "Created invalidation: $INVALIDATION_ID"
          aws cloudfront wait invalidation-completed --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION }} --id $INVALIDATION_ID
          
      - name: Slack Notification On Deployment Status
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: author,action,eventName,ref,workflow
          author_name: ViewSonic Production Deployment Status
          mention: ${{ github.actor }}
          if_mention: success,failure
          job_name: Deploy-to-Viewsonic
          channel: managex-school
          username: manageX-school
          text: |
            ${{ job.status == 'success' && format(':rocket: Deployment to ViewSonic Production environment triggered by @{0} is {1}.', github.actor, job.status) || format(':x: Deployment to ViewSonic Production environment triggered by @{0} is {1}.', github.actor, job.status) }}
            *Author:* `${{ github.actor }}`
            *Deployment for commit* *${{ needs.Docker-Build.outputs.commit_sha }}* *pushed by* *@${{ github.actor }}* has *${{ job.status }}* in *ViewSonic Production Environment*.
            *Workflow Run:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            *Message:* *${{ github.event.inputs.prod_tag }}*
            ${{ job.status == 'success' && 'The code has been deployed to ViewSonic Production Environment. Please check the deployment and verify the changes on the server.' || 'The code has not been deployed to ViewSonic Production Environment due to failure. Please check the deployment logs for more details.' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
